#!/bin/bash -
#
# Copyright (c) 2019 - Adjacent Link LLC, Bridgewater, New Jersey
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
# * Neither the name of Adjacent Link LLC nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

usage="usage: etce-populate-knownhosts.sh [-u USER] [-p SSHPORT] [-k SSHKEYFILE ] HOSTFILE"

user='root'

sshport=22

sshkey=

while getopts "u:p:k:h" opt; do
    case $opt in
        p) sshport=$OPTARG;;
        k) sshkey=$OPTARG;;
        u) user=$OPTARG;;
        h) echo ${usage} && exit 0;;
        \?) exit 1;;
    esac
done

shift $((OPTIND-1))

if [ ! $# == 1 ]; then
  echo ${usage}
  exit 1
fi

hostfile=$1

for host in $(etce-list-hosts ${hostfile}); do
    if [ $sshkey ]; then
        ssh ${user}@${host} -p ${sshport} -i ${sshkey} -o HostKeyAlgorithms=ssh-rsa -o HashKnownHosts=no 'hostname';
    else
        ssh ${user}@${host} -p ${sshport}              -o HostKeyAlgorithms=ssh-rsa -o HashKnownHosts=no 'hostname';
    fi
done
